# Generated by Django 5.2.3 on 2025-06-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_id',
            field=models.CharField(help_text='Unique identifier for the month in Westencontre-MM format.', max_length=7, primary_key=True, serialize=False),
        ),
    ]
