# Generated by Django 5.2.3 on 2025-06-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_month_month_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='owner',
            field=models.CharField(choices=[('shared', 'Shared'), ('keith', 'Keith'), ('tild', 'Tild')], default='shared', help_text='The owner or responsible party for this budget item.', max_length=50),
        ),
    ]
