# Generated by Django 5.2.3 on 2025-06-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budgetitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitemversion',
            name='is_one_off',
            field=models.BooleanField(default=False, help_text='If true, this version is a one-off and does not roll over to future months.'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_id',
            field=models.CharField(help_text='Unique identifier for the month in YYYY-MM format.', max_length=7, primary_key=True, serialize=False),
        ),
    ]
