# Generated by Django 5.2.3 on 2025-06-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_budgetitem_item_name_alter_month_month_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='bills_pot',
            field=models.BooleanField(default=False, help_text="If true, this item is considered part of the 'bills pot'."),
        ),
    ]
