# Generated by Django 5.2.3 on 2025-06-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budgetitem_bills_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Monthly Value'), ('weekly_count', 'Weekly Value by Occurrence Count')], default='fixed', help_text="Defines how the item's monthly value is calculated.", max_length=20),
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='weekly_payment_day',
            field=models.IntegerField(blank=True, help_text="Day of the week for weekly_count items (1=Mon, ..., 7=Sun). Only relevant if Calculation Type is 'Weekly Value by Occurrence Count'.", null=True),
        ),
        migrations.AlterField(
            model_name='budgetitemversion',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text="The budgeted amount for this item for this month/version. For 'weekly_count' items, this is the weekly value.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_id',
            field=models.CharField(help_text='Unique identifier for the month in YYYY-MM format.', max_length=7, primary_key=True, serialize=False),
        ),
    ]
