# Generated by Django 5.2.3 on 2025-06-30 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_budgetitem_calculation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='last_payment_month',
            field=models.ForeignKey(blank=True, help_text='Optional: The last month this item will be active. It will not appear in subsequent months.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminating_items', to='budget.month'),
        ),
    ]
