# Generated by Django 5.2.3 on 2026-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_budgetitem_last_payment_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='budgetitemversion',
            name='notes',
        ),
    ]
