# Generated by Django 5.2.3 on 2026-04-29 14:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_budgetitem_groceries_pot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='What was purchased.', max_length=200)),
                ('paid_by', models.CharField(choices=[('keith', 'Keith'), ('tild', 'Tild')], help_text='Who paid for it.', max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost of the item.', max_digits=10)),
                ('amount_owed', models.DecimalField(decimal_places=2, help_text='How much the other person owes (defaults to 50% but can be overridden).', max_digits=10)),
                ('date_added', models.DateField(help_text='When the expense occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tab Item',
                'verbose_name_plural': 'Tab Items',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='TabRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount repaid.', max_digits=10)),
                ('paid_by', models.CharField(choices=[('keith', 'Keith'), ('tild', 'Tild')], help_text='Who made the repayment.', max_length=50)),
                ('date', models.DateField(help_text='When the repayment was made.')),
                ('note', models.CharField(blank=True, default='', help_text='Optional note.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tab Repayment',
                'verbose_name_plural': 'Tab Repayments',
                'ordering': ['-date'],
            },
        ),
    ]
