# Generated by Django 5.2.3 on 2026-04-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_tabitem_tabrepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='is_tab_repayment',
            field=models.BooleanField(default=False, help_text="If true, each month's value is automatically added as a tab repayment."),
        ),
    ]
