# Generated by Django 5.2.3 on 2026-05-02 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_expense_pot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='item_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('savings', 'Savings')], default='expense', help_text="Type of the item: 'expense' or 'income'.", max_length=10),
        ),
        migrations.CreateModel(
            name='NurserySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nursery_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nursery Settings',
                'verbose_name_plural': 'Nursery Settings',
            },
        ),
    ]
