# Generated by Django 5.2.3 on 2026-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_alter_budgetitem_item_type_nurserysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='is_nursery_linked',
            field=models.BooleanField(default=False, help_text="If true, this item's monthly value can be auto-synced from the Nursery cost calculator's Transfer to TFC total."),
        ),
    ]
