# Generated by Django 5.2.3 on 2026-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_alter_budgetitem_childcare_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='bills_pot_owner',
            field=models.CharField(blank=True, choices=[('shared', 'Shared'), ('keith', 'Keith'), ('tild', 'Tild')], default='', help_text='For Bills Pot expenses, whose bills pot funds it. Overrides `owner` for attribution (whose card/total the item counts under). Empty for non-bills items.', max_length=50),
        ),
    ]
