# Generated by Django 5.2.3 on 2026-07-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_budgetitem_bills_pot_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='bills_pot_owner',
        ),
    ]
