# Generated by Django 5.2.3 on 2026-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_remove_budgetitem_bills_pot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('groceries', 'Groceries'), ('subscriptions', 'Subscriptions'), ('car', 'Car')], default='', help_text='Optional bill category used to group expenses on the budget page.', max_length=20),
        ),
    ]
