# Generated by Django 5.2.3 on 2026-08-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_budgetitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='category',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('groceries', 'Groceries'), ('subscriptions', 'Subscriptions'), ('car', 'Car'), ('children', 'Children')], default='', help_text='Optional bill category used to group expenses on the budget page.', max_length=20),
        ),
    ]
