# Generated by Django 5.2.3 on 2026-08-30 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_alter_budgetitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Royal London pension'.", max_length=100)),
                ('owner', models.CharField(choices=[('shared', 'Shared'), ('keith', 'Keith'), ('tild', 'Tild')], help_text='Whose wealth this is — drives the per-person vs joint FIRE views.', max_length=50)),
                ('kind', models.CharField(choices=[('pension', 'Pension'), ('isa', 'ISA'), ('cash', 'Cash savings'), ('gia', 'General investment')], help_text='Pension wealth is locked until pension access age; the other kinds are accessible and can bridge an early retirement.', max_length=20)),
                ('provider', models.CharField(blank=True, default='', help_text="Optional provider name, e.g. 'Monzo'.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FIRE Account',
                'verbose_name_plural': 'FIRE Accounts',
                'ordering': ['owner', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FireSettings',
            fields=[
                ('owner', models.CharField(choices=[('keith', 'Keith'), ('tild', 'Tild')], max_length=50, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, help_text='Used to convert projection dates to ages and pick the pension access age.', null=True)),
                ('expected_real_return_pct', models.DecimalField(decimal_places=2, default=3.5, help_text='Expected annual investment return AFTER inflation, %.', max_digits=5)),
                ('safe_withdrawal_rate_pct', models.DecimalField(decimal_places=2, default=4.0, help_text='Withdrawal rate defining the FI number (annual spending ÷ this %).', max_digits=5)),
                ('target_retirement_age', models.IntegerField(blank=True, help_text='Optional target age, used for the Coast FIRE number.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FIRE Settings',
                'verbose_name_plural': 'FIRE Settings',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Home', help_text='Display name for the property.', max_length=100)),
                ('property_value', models.DecimalField(decimal_places=2, help_text='Estimated current property value.', max_digits=12)),
                ('property_value_date', models.DateField(help_text='When the property value estimate was made.')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Outstanding mortgage balance as of balance_date.', max_digits=12)),
                ('balance_date', models.DateField(help_text='The date the stated balance was correct.')),
                ('interest_rate_pct', models.DecimalField(decimal_places=2, help_text='Annual interest rate %.', max_digits=5)),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='Total monthly payment (capital + interest).', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mortgage',
                'verbose_name_plural': 'Mortgages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EarningsVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(choices=[('keith', 'Keith'), ('tild', 'Tild')], max_length=50)),
                ('effective_from', models.DateField(help_text='The date these terms start applying from.')),
                ('gross_annual_salary', models.DecimalField(decimal_places=2, help_text='Gross annual salary before any salary sacrifice.', max_digits=12)),
                ('employee_pension_pct', models.DecimalField(decimal_places=2, default=0, help_text='Employee pension contribution as % of gross salary.', max_digits=5)),
                ('employee_pension_is_salary_sacrifice', models.BooleanField(default=True, help_text='If true, the employee contribution is salary-sacrificed (reduces taxable gross).')),
                ('employer_pension_pct', models.DecimalField(decimal_places=2, default=0, help_text='Employer pension contribution as % of gross salary.', max_digits=5)),
                ('note', models.CharField(blank=True, default='', help_text="Optional note, e.g. 'promotion'.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Earnings Version',
                'verbose_name_plural': 'Earnings Versions',
                'ordering': ['-effective_from'],
                'unique_together': {('owner', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='The date this balance was observed.')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Balance on that date.', max_digits=12)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('monzo', 'Monzo sync')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='budget.fireaccount')),
            ],
            options={
                'verbose_name': 'Balance Snapshot',
                'verbose_name_plural': 'Balance Snapshots',
                'ordering': ['-date'],
                'unique_together': {('account', 'date')},
            },
        ),
    ]
