# Generated by Django 5.2.3 on 2026-08-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_fireaccount_firesettings_mortgage_earningsversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firesettings',
            name='include_state_pension',
            field=models.BooleanField(default=True, help_text='If true, the full new state pension is added to retirement income from state pension age.'),
        ),
        migrations.AddField(
            model_name='firesettings',
            name='pension_access_age',
            field=models.IntegerField(default=57, help_text='Age pension wealth unlocks. 57 from April 2028 (Finance Act 2021); set 58 to anticipate the expected-but-unlegislated rise alongside state pension age 68.'),
        ),
    ]
