# Generated by Django 5.2.3 on 2026-08-30 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_firesettings_include_state_pension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # An earlier Monzo integration (dropped in f081d75, April 2026) left a
        # "budget_monzoconnection" table behind in existing databases with an
        # incompatible schema — its migration was deleted from the tree, so
        # Django doesn't know about it and CreateModel below would collide.
        # Its only contents are that integration's dead OAuth tokens, which
        # are worth purging anyway. The other leftovers from that era
        # (budget_monzotransaction, budget_monzomerchantmapping) don't collide
        # and are deliberately left alone.
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "budget_monzoconnection"',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='fireaccount',
            name='monzo_pot_id',
            field=models.CharField(blank=True, default='', help_text="If set, 'Sync from Monzo' writes this pot's balance as a snapshot on this account.", max_length=100),
        ),
        migrations.CreateModel(
            name='MonzoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('monzo_user_id', models.CharField(blank=True, default='', max_length=100)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monzo_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monzo Connection',
                'verbose_name_plural': 'Monzo Connections',
            },
        ),
    ]
