# Generated by Django 5.2.3 on 2026-08-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_property_split_from_mortgage'),
    ]

    operations = [
        migrations.AddField(
            model_name='firesettings',
            name='expected_annual_savings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional override: how much this person actually invests per year (accessible, non-pension). Blank = derive it from the budget's savings lines — set this when those lines include money that gets spent (e.g. fun-money pots).", max_digits=12, null=True),
        ),
    ]
