# Generated by Django 5.2.3 on 2026-09-07 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0030_firesettings_expected_annual_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'Autumn 2026'.", max_length=50, unique=True)),
                ('start_date', models.DateField(help_text='First school day of the term.')),
                ('end_date', models.DateField(help_text='Last school day of the term.')),
            ],
            options={
                'verbose_name': 'School Term',
                'verbose_name_plural': 'School Terms',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='term_payment_timing',
            field=models.CharField(blank=True, choices=[('', '—'), ('start', 'Paid at start of term'), ('end', 'Paid at end of term')], default='', help_text='For per_term items: whether the bill lands in the first or the last month of each SchoolTerm. The stored value is the cost per term; the monthly budget figure is that value accrued evenly over the months since the previous payment.', max_length=5),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Monthly Value'), ('weekly_count', 'Weekly Value by Occurrence Count'), ('per_term', 'Per School Term')], default='fixed', help_text="Defines how the item's monthly value is calculated.", max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='childcare_link',
            field=models.CharField(blank=True, choices=[('', '—'), ('ellis_nursery', 'Ellis nursery'), ('gaspard_care', 'Gaspard breakfast/after-school'), ('gaspard_holiday', 'Gaspard holiday club'), ('gaspard_term_club', 'Gaspard term-time clubs')], default='', help_text="If set, this item's monthly value is auto-synced from the childcare calculators: 'ellis_nursery' → Ellis's Transfer to TFC, 'gaspard_care' → Gaspard's breakfast + after-school net, 'gaspard_holiday' → his holiday-club net, 'gaspard_term_club' → the accrued monthly set-aside for his term-time clubs (paid up front each term).", max_length=20),
        ),
    ]
