# Generated by Django 5.2.3 on 2026-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0032_seed_school_terms_2026_27'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='childcare_link',
            field=models.CharField(blank=True, choices=[('', '—'), ('childcare', 'Childcare (nursery + all clubs)'), ('ellis_nursery', 'Ellis nursery (legacy)'), ('gaspard_care', 'Gaspard after-school (legacy)'), ('gaspard_holiday', 'Gaspard holiday club (legacy)'), ('gaspard_term_club', 'Gaspard term-time clubs (legacy)')], default='', help_text="If set, this item's monthly value is auto-synced from the childcare calculators. 'childcare' → the whole monthly cost: Ellis's nursery net plus Gaspard's after-school, term-time-club and holiday-club attendance for the month (TFC clubs at their net 80%, non-TFC at full price). The other values are legacy per-component links consolidated by migration 0034; they remain only on expired items.", max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='term_payment_timing',
            field=models.CharField(blank=True, choices=[('', '—'), ('start', 'Paid at start of term'), ('end', 'Paid at end of term')], default='', help_text='For per_term items: whether the bill lands in the month a SchoolTerm starts or the month it ends. The stored value is the cost per bill; it appears in the budget only in the months a bill lands — no smoothing.', max_length=5),
        ),
    ]
